# Generated by Django 3.1.4 on 2020-12-15 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.course')),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('total_seats', models.IntegerField()),
                ('open_seats', models.IntegerField()),
                ('waitlist_seats', models.IntegerField()),
                ('holdfile_seats', models.IntegerField()),
                ('professor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.professor')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.section')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.department'),
        ),
    ]
