# Generated by Django 3.1.4 on 2020-12-17 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='season',
            new_name='month',
        ),
    ]
