# Generated by Django 3.1.4 on 2020-12-24 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201217_0043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['start_date']},
        ),
        migrations.RemoveField(
            model_name='day',
            name='professor',
        ),
        migrations.AddField(
            model_name='section',
            name='professor',
            field=models.ManyToManyField(to='api.Professor'),
        ),
        migrations.AddField(
            model_name='semester',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
