# Generated by Django 3.1.4 on 2020-12-25 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201225_0048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='professor',
            new_name='professors',
        ),
    ]
