# Generated by Django 3.1.4 on 2020-12-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201225_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='gened',
        ),
        migrations.AddField(
            model_name='course',
            name='geneds',
            field=models.ManyToManyField(blank=True, to='api.GenEd'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
