# Generated by Django 3.1.4 on 2020-12-25 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201225_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='semester',
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.semester'),
            preserve_default=False,
        ),
    ]
