# Generated by Django 3.1.4 on 2021-01-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='slug',
            field=models.SlugField(default='prof', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='semester',
            name='num_days',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
